### ISSUE TITLE
Overriding field markup

### ISSUE THREAD

**Issue by stevieg83** [am-impact/amforms#100]
I get that I need to override `field` by creating a new Twig template inside my template directory like `_amforms/field.twig` as an example and that will give me control over the outer wrappers.

What about actually altering the form field class itself? Do I also need to copy the component directory as well to override?

**Comment by jsunsawyer** [comment]
I am also looking for this functionality. There is another open issue #55 asking about this and on #75 the author says this functionality doesn't currently exist.

It'd be great if we could at least get a way to manually check field types and include our own field templates. I'm close, but I don't know how to set/pass "config" from the field template.

```
{% if type in ["test","something","dropdown"] %}
  {% switch type %}
    {% case "dropdown" %}
      {% include "_includes/forms/select" with config only %}
  {% endswitch %}
{% else %}
  {{ input|raw }}
{% endif %}
```

**Comment by stevieg83** [comment]
closing as a dupe of #75
