### ISSUE TITLE
Dynamic email recipients

### ISSUE THREAD

**Issue by rswhite7** [am-impact/amforms#101]
Hi, I have a situation where I need a form to submit and be sent to my company's email address AND to an email address outputted from an email field from the entry that the form sits on.  Is it possible to have a hidden input in the template that contains the email addresses I want the notification to go to?

**Comment by hubertprein** [comment]
You'll have to do something like this: #86

**Comment by rswhite7** [comment]
Thanks so much, @hubertprein!  I got it working.  I had also created a ticket the other day on stackexchange, and so I've gone ahead and answered it based on the other closed tickets so hopefully that will cut down on the repeat questions sent your way.

http://craftcms.stackexchange.com/questions/17309/dynamic-email-recipients-with-amforms/17327

**Comment by rswhite7** [comment]
Hi @hubertprein, I actually have one last question.  I have a dropdown in my template where someone chooses a name in the dropdown.  The value of that <option> will have 1-3 email addresses in them like:

`value="email-1@domain.com,email-2@domain.com,email-3@domain.com"`

In my form settings, I have the notification email set to:

`default@domain.com,{notificationRecipients}`

Everything works if the dropdown value has _one_ email address in it.  If it has more than one, it doesn't work, regardless if there is a space after the comma separating the addresses or not.  Am I not understanding how to do this? Should I not be using commas with no spaces to separate the addresses?  I believe this was tested last week but I guess I missed something in my tests.  What is the correct way to list multiple email addresses?

Thanks again!

**Comment by rswhite7** [comment]
Hi @hubertprein, sorry to bug you. Is it possible to get an answer on this today?

I see `$recipients = ArrayHelper::stringToArray($form->notificationRecipients);` on line 230 of the AmForms_SubmissionsService.php file, which seems like it should do the trick just fine.  I've tried exchanging the dropdown for a hidden text input as a test but it has the same effect.

**Comment by oadslug** [comment]
Hi @rswhite7. Did you ever resolve this issue? I am having the same problem. 

I also have the notification field set to: `default@domain.com, {notificationRecipients}`

`notificationRecipients` in this case is 1 or more comma separated emails (created by copying addresses from a checkbox list to the `notifcationRecipients` field via javascript). It will send to the static address (default@domain.com) and a single dynamic address, but not to more than one dynamic address. 

I've tried spaces, no spaces, between addresses. 
I've tried using the `|raw` filter, in case it was an encoding issue.
I've also hard coded the notification field with the same addresses to rule out a server issue, which seems to work fine.

Running out of ideas. Any help would be much appreciated. Thanks.

**Comment by oadslug** [comment]
Hi @rswhite7. I think I discovered the problem. It looks like the dynamic `{notificationRecipients}` is being treated as a single email entry and thus not passing the email filter when there is more than one email defined.

I modified the plugin to split the string and process each entry separately (line 347 of AMForms_SubmissionService):

```
// Send emails
            foreach ($recipients as $recipient) {
                $notificationEmail->toEmail = $this->_translatedObjectPlusEnvironment($recipient, $submission);
                
                // Split multiple emails defined in dynamic twig variables
                $emails = array_map('trim', explode(',', $notificationEmail->toEmail));
                foreach($emails as $email) {
                    $notificationEmail->toEmail = $email;
                    if (filter_var($notificationEmail->toEmail, FILTER_VALIDATE_EMAIL)) {
                        if (craft()->email->sendEmail($notificationEmail, array('amFormsSubmission' => $submission))) {
                            $success = true;
                        }
                    }
                }
                
            }
```

I'll submit a separate issue and see if they want to add this to master (or deal with it in a different way).

**Comment by rswhite7** [comment]
Hi @oadslug, unfortunately @hubertprein never got back to me on how to solve this.  I eventually figured out the notification recipients was just an array and I could grab each email individually with this syntax:

`notifications@domain.com,{notificationRecipients[0]},{notificationRecipients[1]},{notificationRecipients[2]},{notificationRecipients[3]},{notificationRecipients[4]},{notificationRecipients[5]}`

This gave me up to 6 dynamic email values from my form.  I just had to tell my client not to output more than 6 on the front end.  It's obviously not the best solution because it doesn't accommodate more than what you put in the notifications field in the backend, but it's what I found.

I'm currently learning plugin development, so I suspect that the more ideal solution would to be to output some sort of entry id into the form, and then use that to search for the email addresses in that entry via its posted id in the backend with the `onEmailSubmission` event.

**Comment by oadslug** [comment]
Ha... looks like our comments just missed each other. Thanks for getting back to me (that's ingenious! I would have never thought of that). I got my hands dirty in the plugin, and seems to be working now. I also submitted a new issue [#114 ](https://github.com/am-impact/amforms/issues/114). We'll see if they incorporate it. Thanks again. Have a great weekend.

**Comment by rswhite7** [comment]
@oadslug Yeah I didn't really have much of a choice and was already well over my deadline at the time.  Obviously, doing it all in the back end instead of printing a bunch of people's email addresses to the frontend is a far better (and maybe more legal?) way of doing things, but it's all I could figure out.

Glad you got yours sorted though!  Cheers!
