### ISSUE TITLE
Update to 1.6.0 fails and causes database rollback

### ISSUE THREAD

**Issue by NickWalkers** [am-impact/amforms#103]
Hi,

Just tried to update to v 1.6.0 but was unable to do so. Caused a craft error and required a rollback. Any advice on how to fix this issue?

Cheers

**Comment by pixeldeluxe** [comment]
Hi,

I got the same problem (from 1.4.0 to 1.6.0).
Keep up the good work!

Grtz,
Martijn

**Comment by AbbeyDesign** [comment]
Same here.

**Comment by hubertprein** [comment]
Fixed in the latest release!

**Comment by pixeldeluxe** [comment]
Yeah, it works! Tnx.

**Comment by NickWalkers** [comment]
Thanks for the fix. Much appreciated.
