### ISSUE TITLE
Key "confirmationTemplate" does not exist

### ISSUE THREAD

**Issue by afairhurst** [am-impact/amforms#109]
**Page:**
a&m forms > Setting > General > Templates

**Error:**
> Key "confirmationTemplate" for array with keys "fieldTemplate, formTemplate, notificationTemplate, tabTemplate" does not exist

**Description**
Page won't load due to error. Settings for Templates are unavailable.

**Version**
1.6.1 (no issue with 1.4.5)
Craft CMS 2.6.2950

**Comment by BryceBubbles** [comment]
Seems to only happen before saving your first form.

**Comment by raymondelooff** [comment]
I've created a pull request #110 that fixes this issue.
