### ISSUE TITLE
Date and Time fields datepicker JS has wrong ID

### ISSUE THREAD

**Issue by kotyy** [am-impact/amforms#123]
The jQuery UI date and time pickers are not initializing properly because the generated ID for the javascript does not match the generated ID on the form fields.

For example:
date field ID: form_DQQeGSpVh1-fields-dateTime-date
JS selector ID: fields-form_DQQeGSpVh1\x2DdateTime\x2Ddate

**Comment by mbdour** [comment]
the date.html template at: amforms/templates/_display/templates/_includes/forms/date.html shall be edited. Line 18 should be like this:
var $datePicker = $('#{{ ('fields-' ~ id) |namespaceInputId }}');

the escape filter was removed so it does not replace dashes with its escaped characters.
also, the id shall include "fields-" then it is filtered by namespaceInputId.

Hope this helps.

**Comment by kotyy** [comment]
@mbdour Thank you! I played with that, but couldn't get it just right.
