### ISSUE TITLE
Simple field value tag for email notification

### ISSUE THREAD

**Issue by kaspar-allenbach** [am-impact/amforms#133]
Is it possible to get the value of a field in the `notification template` without creating a loop?

I need to create a link with url params and this would be soooo much easier without looping:

```
href="
  domain.com/createinvoice?
  email={# value of email field #}
  &comment={# value of hidden field#}
  %20{# value of text field #}"
```

I tried every variation of a field tag but nothing works.

> {{ field.emailAdress.value }} no
> {{ emailAdress.value.first() }} no
> {{ tab.emailAddress.value }} no
> ???

Is this even possible?

**Comment by hubertprein** [comment]
The submission itself is available in the template. So I reckon something like `{{ submission.yourFieldHandleHere }}` should give you the value.

**Comment by icopp** [comment]
Is there any way to access this submission info in the form template itself? There's some things I'd like to show up alongside the "thank you for your submission" message on the result page, rather than be emailed out.

**Comment by hubertprein** [comment]
You are able to add the submissionId to the redirect URL (`?submissionId={id}`), and simply get that info with `{{ craft.amForms.submissions({'id': craft.request.getParam('submissionId').first() }}`

However, I wouldn't recommend doing that, as your visitors are able to adjust the ID and simply display other information on the results page. Which is not what you want. You'll have to create a system around it so people can't fool your website with ID adjustments.
