### ISSUE TITLE
"Jquery is not defined" error on date/time field

### ISSUE THREAD

**Issue by nilsenpaul** [am-impact/amforms#135]
Hi guys,

On using a date/time field, I get a `jQuery not defined` error. Jquery is loaded through includeJsFile (first), but the locale asset gets loaded before jQuery ... Any suggestions?

![schermafbeelding 2017-03-28 om 09 27 29](https://cloud.githubusercontent.com/assets/6794819/24393669/39ca58f4-1399-11e7-89d4-dacb89c398b1.png)

**Comment by hubertprein** [comment]
Yeah I ran into the same issue the other day. I don't like how the date field works, at all. I rather have that thing working as an advanced field where developers have the free will to make it work the way they like it, rather than support it by default (as a basic field).

**Comment by hubertprein** [comment]
jQuery removed from the fields in the latest release. You hold the power now.
