### ISSUE TITLE
Custom notifications

### ISSUE THREAD

**Issue by fantasticmachine** [am-impact/amforms#139]
Hi there, 

Forgive me if I'm missing something, but is there any documentation on how to produce a custom notification template?

I've got notifications working  but I'm trying to set up some custom HTML to format the notification but can't figure out how to make it work.

**Comment by hubertprein** [comment]
You specify the template in the form settings. In your craft/templates folder simply create a folder with the path you specified in the settings. So let's say you specified: `_amforms/myNotification`. The following template should be created here: `craft/templates/_amforms/myNotification.twig`

**Comment by fantasticmachine** [comment]
Absolutely understand that. I didn't phrase my question properly. 
I was trying to work out how to access the submitted data in the notification template.

I have since discovered you must use `{{ submission.myFieldName }}`. But I couldn't see this in the docs anywhere. I had to go looking for the default template and work out what was going on.

**Comment by hubertprein** [comment]
That is currently the best way to that indeed. Docs is something that could really use an update. However, that's something we're going to save until Craft 3 comes out. Since we're busy updating it to run on that version.
