### ISSUE TITLE
Settings not available?

### ISSUE THREAD

**Issue by MattWilcox** [am-impact/amforms#14]
How do I get to the Settings to enable reCAPTCHA? 

Going to Plugins lists the plugin as active, but the plugin does not have a clickable link to go to a settings page?

**Comment by hubertprein** [comment]
Do you have the latest version? If you do, you should see a link in the plugins list.

If you have an older version, you can click the tab in the CP, and you'll see a settings icon next to the plugin name. Like this: http://cl.ly/image/05081L3F3T3H
