### ISSUE TITLE
Cannot read property 'regional' of undefined

### ISSUE THREAD

**Issue by andregoldstein** [am-impact/amforms#140]
Hi there, running into an issue with the datepicker, pointing to the `datepicker-fr.js` file, do you have any ideas what might be causing it?

If not, don't worry I'll revert to a plain text field and bring in my own datepicker.

Thanks!

**Comment by hubertprein** [comment]
I'd suggest you go for a plain text field instead, just like you said. That's currently the best way to do it, as the date picker will be removed soon.

**Comment by andregoldstein** [comment]
Thanks, small suggestion perhaps it could remain a field that adds a class such as `date` to the field, that could provide a hook for front-end JS work?

**Comment by hubertprein** [comment]
I'm thinking about using a input `type=date'` with a class added to it perhaps. So rather than automatically using jQuery for the date picker, give developers some freedom.

**Comment by andregoldstein** [comment]
Thanks Hubert sounds perfect. Cheers 👍
