### ISSUE TITLE
Exports with Criteria of type Checkbox do not behave correctly

### ISSUE THREAD

**Issue by MattWilcox** [am-impact/amforms#141]
When exporting from a form the following should happen:

1 - With no Criteria set, the full set of records should be output.
2 - With a Criteria set which is of field type checkbox, that is not checked, I should get an export containing only records that *do not* have the checkbox field checked
3 - With a Criteria set which is of type checkbox, that is checked, I should get an export of only records that *do* have the checkbox field checked

2 does not work. With a Criteria set, but the box unchecked, the criteria is ignored and you get the same results you'd get from 1

This means it is impossible to export only records where a checkbox field has not been checked.

**Comment by hubertprein** [comment]
Fixed in the latest release.
