### ISSUE TITLE
get handle of form via field type Form

### ISSUE THREAD

**Issue by rolfkokkeler** [am-impact/amforms#147]
I created a Form field selector ( field type Form ) for an entry.
How do I get the handle from this entries selected form?

entry.ContactAppointmentForm.handle or getHandle() does not seem to do the trick

![screen shot 2017-05-29 at 15 05 16](https://cloud.githubusercontent.com/assets/16954726/26550908/4d23c26a-4480-11e7-98a7-c8f2d0fe64d9.png)

**Comment by hubertprein** [comment]
Automatically:
```
{{ entry.ContactAppointmentForm.first().displayForm() }}
```

Your own way:
```
{% set myForm = entry.ContactAppointmentForm.first() %}

{{ myForm.handle }}
{{ myForm.displayField('fieldHandleHere') }}
etc..
```

**Comment by rolfkokkeler** [comment]
Hubert,

thanx for the answer, I missed your comment six days ago

**Comment by hubertprein** [comment]
No problem, glad I could help :)
