### ISSUE TITLE
multi env settings?

### ISSUE THREAD

**Issue by rolfkokkeler** [am-impact/amforms#149]
is there anyway to set multi enviroment settings for fields such as mailto or mailfrom?

`        'environmentVariables' => array(
            'basePath' => $_SERVER["DOCUMENT_ROOT"],
            'baseUrl'  => 'http://local.surlogic.bert.works',
            'mailto'	=> 	'control@bert.house',
            'mailfrom'	=>	'control@bert.house'
        ),       `

**Comment by hubertprein** [comment]
The `fromEmail`, `fromName` and `toEmail` are all parsed through the submission variable and the environment variables. So something like `{mailto}` in the form settings, should work.
