### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by mmc501** [am-impact/amforms#152]
The Checkboxes field doesn't appear to work.
If I display the form by:
{{ craft.amForms.displayForm('formHandle') }}
or the field by 
{{ form.displayField('fieldHandle') }}
My Checkbox field simply doesn't display.

I tried using this:

```
<p><label><input type="checkbox" id="frm_checkbox_groep" name="fields[iWouldLikeToBeContactedRegarding][]" value="Boiler Check"> Boiler Check</label></p>
<p><label><input type="checkbox" id="frm_checkbox_groep" name="fields[iWouldLikeToBeContactedRegarding][]" value="Service Care"> Service Care</label></p>
<p><label><input type="checkbox" id="frm_checkbox_groep" name="fields[iWouldLikeToBeContactedRegarding][]" value="Heating Controls"> Heating Controls</label></p>
<p><label><input type="checkbox" id="frm_checkbox_groep" name="fields[iWouldLikeToBeContactedRegarding][]" value="Carbon Monoxide Detectors"> Carbon Monoxide Detectors</label></p>
<p><label><input type="checkbox" id="frm_checkbox_groep" name="fields[iWouldLikeToBeContactedRegarding][]" value="Heating System Cleanse"> Heating System Cleanse</label></p>
```

But the checkbox does not get displayed in the Submissions area of the control panel or the email.

How should checkboxes be used with AMForms?

**Comment by hubertprein** [comment]
Are you a 100% sure you've got the field in the fieldlayout of that form?

**Comment by mmc501** [comment]
Ah - I'm a wally - I hadn't it added.
 I've been looking at this for ages and trying all sorts - thanks for clarifying.
Had added that field afterwards.

**Comment by hubertprein** [comment]
No problem. Glad you got it sorted out.
