### ISSUE TITLE
Click on submission results in error "Impossible to invoke a method ("id") on a null variable."

### ISSUE THREAD

**Issue by chromadesign** [am-impact/amforms#160]
My forms are working fine and emails are sent without a problem. But when I click on a submission in the backend I get a template error saying "Impossible to invoke a method ("id") on a null variable.", see screenshot below. 
![screenshot](https://user-images.githubusercontent.com/18714537/32134867-40453f2c-bbf6-11e7-83a7-0235ce1c5669.JPG)

**Comment by hubertprein** [comment]
Souds like something else might be going wrong on your end, as I can't reproduce this. The only `.id` that is happening there, is on `craft.users`. Which should be working just fine, as craft.users can't be `null`.

**Comment by hubertprein** [comment]
That's weird indeed. Glad it got solved though!

If it happens again, reopen the issue and we'll see if we can reproduce it.

**Comment by akuales** [comment]
I do have the same problem now after trying to post forms via ajax.
At some point I couldn't open any submission anymore from any other form I created.

**Comment by haabe** [comment]
I experience this error as well, but not using Ajax.

I think it might be related to whether you are logged into Craft as a user or not when submitting the form.

**Comment by chasegiunta** [comment]
Also experiencing this problem.

**Comment by chasegiunta** [comment]
@hubertprein This stems from the version of Craft you have. `craft.users` will be `null` if you're on a Personal or Client license, as Craft doesn't allow users. Just to test, you can try to output `craft.users` method in any twig template and it will break.

Upgrading to Craft Pro license fixes this.
