### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [am-impact/amforms#17]
How do I set up notification emails to be sent when a form is submitted?

I was looking in general > config there was an option to use mandril but it requires the 
"a&m mailer in order to work"

Thanks!

**Comment by Ramshackle-Jamathon** [comment]
Ended up using PHPMail but I'm still currious about the "a&m mailer" I can't seem to find it online

**Comment by hubertprein** [comment]
I should've let the **use mandrill** option out of the settings for now, as I've no idea when I'm actually going to implement it in the plugin.

When you create a new form, the **send notifications** option under the notifications tab, is enabled by default. Which uses EmailModel and service from Craft.

**Comment by Ramshackle-Jamathon** [comment]
Cool! thanks for the quick reply
