### ISSUE TITLE
Front end output entries and custom templates

### ISSUE THREAD

**Issue by noregt** [am-impact/amforms#25]
Two 'issues' using your excellent form:
•  I'm missing the frontend code to display entries. Is that possible? Or no web page entries output?
• Also examples of the custom templates to adapt the html and css I would be useful (form.html, field.html etc)

**Comment by noregt** [comment]
Found the answer to custom templates in the archived issues: copying craft/plugins/amforms/templates/_display/templates to the custom folder works.

**Comment by hubertprein** [comment]
You can use the variable functions for that, just as you would display a form. If you use the **submissions** (get a criteria model) or **getSubmissionById** (when you know the exact ID..) function, one could get the submission data, which you could display on the frontend.

With the code below you can get multiple submissions, based on a form.

```
{% set submissions = craft.amForms.submissions({
    formHandle: 'yourFormHandleHere'
}) %}
```

**Comment by noregt** [comment]
Thanks Hubert!

**Comment by nunocarrico** [comment]
Hello! Is possible to show a file submited from a form in frontend? I can display other fields (name, email, etc).

Thank you for your great work.
