### ISSUE TITLE
Twig Includes do not work when using A&M Forms

### ISSUE THREAD

**Issue by bgarrant** [am-impact/amforms#26]
When I use a form on a page that has a twig include such as:

``` {% include "_includes/our_clients_say" %} ```

I get the error: Unable to find the template “_includes/our_clients_say”.  The path is correct and works fine on all pages that do not use Forms tag.  Any idea why?

**Comment by hubertprein** [comment]
@bgarrant Should be fixed with the latest release. Mind that it's updated for Craft 2.5, so you'd best wait a day before updating, if you're not using the beta.
