### ISSUE TITLE
Customizing the body of the notification

### ISSUE THREAD

**Issue by matanlevkowich** [am-impact/amforms#30]
Great plugin!! 
One small point. How can I customize the body of the automatic notification email? 
Thanks!

**Comment by hubertprein** [comment]
When you edit a form, you have a few tabs. The templates tab let's you customize the template you want to use for your email. If you enter a folder here (e.g.: _amforms), it'll look for email.html / email.twig by default. If you enter a folder with the template here (e.g. _amforms/myEmail.twig) it will specifically target this template when sending a notification.

So basically, just make a folder within Craft's template folder. So it'll look like: templates/_amforms/myEmail.twig.

**Comment by matanlevkowich** [comment]
Great, thanks! It is nice to know that you can customize basically everything... I was trying to display in the front end the tab name (tabs that contains the form fields) but without success. I was trying {{ tab.info }} and {{ tab.name }} but it didn't work. Is it actually possible?

**Comment by hubertprein** [comment]
@matanlevkowich Sorry for the late reply, but yes this is possibly. If you dump the tab.info, you'll notice which keys are available to display. In your case, you want to use: {{ tab.info.name }}
