### ISSUE TITLE
Missing SVG icons

### ISSUE THREAD

**Issue by lindseydiloreto** [am-impact/amforms#33]
Granted, this is a brand new feature of Craft 2.5... perhaps you're already working on it.

Some official icons would be great:
 - For the main plugin icon
 - For the side nav mask
 - For the "Recent submissions" widget

Loving this plugin, btw! I recently switched over from P&T Contact Forms, and never realized just how much great stuff I was missing. :)

Thanks, and keep up the great work!

**Comment by hubertprein** [comment]
Very late reply, but thanks for the compliment and wanted to let you know that we're working on this! Going to add icons for all the plugins we've been sharing.

**Comment by lindseydiloreto** [comment]
Great, thanks! :)
