### ISSUE TITLE
Dashboard Widget issues

### ISSUE THREAD

**Issue by lindseydiloreto** [am-impact/amforms#34]
Couple of bugs with the dashboard widget...
 - Can't be extended to 3 columns. For whatever reason, it's limited to 2.
 - Doesn't remember its column width. Refreshing the page snaps it back to a single column.

**Comment by hubertprein** [comment]
@lindseydiloreto Fixed in the latest release!

**Comment by lindseydiloreto** [comment]
Awesome, thanks!
