### ISSUE TITLE
Custom Templates

### ISSUE THREAD

**Issue by mmc501** [am-impact/amforms#35]
I have copied the various templates from plugins templates _display folder: form.twig, tab.twig and field.twig
to /craft/templates/_amforms/
When I create a form and add my template links - same as default: _amforms/field
When the field template is set to that and I try to display the form on the front end I get the error: 

Template Error
Unable to find the template “_components/fieldtypes/PlainText/input”. 

Have I done something wrong?

**Comment by hubertprein** [comment]
@mmc501 Fixed in the latest release!
