### ISSUE TITLE
Error message for unsuccessful reCaptcha attempt

### ISSUE THREAD

**Issue by cibgraphics** [am-impact/amforms#42]
It appears as though there is no error reporting for the captcha. If there isn't can this please be added?

**Comment by hubertprein** [comment]
There is.

Use the following in your custom **form** template (when using the **displayForm** function):
```
{% if element.getErrors('spamFree')|length -%}
    <ul class="errors">
        {% for error in element.getErrors('spamFree') -%}
            <li>{{ error }}</li>
        {% endfor -%}
    </ul>
{% endif -%}
```

Use the following in your custom **HTML** template (when you're not using the **displayForm** function):
```
{% if formHandle is defined %}
    {# Display errors by a macro #}
    {{ errorList(formHandle.getErrors('spamFree')) }}
{% endif %}
```
