### ISSUE TITLE
Custom templates not working

### ISSUE THREAD

**Issue by anguiac7** [am-impact/amforms#43]
I'm developing a site locally and had created templates for both field and form. I set them in the form settings and everything worked. However, when I downloaded my changes (via Git) to my server, the custom templates aren't being called.

I've reinstalled the plugin, deleted and recreated the form, and checked my DB to make sure the value was being saved for the template path, and cleared caches. I've also checked the files and renamed them. Everything looks good on the back end, but when I load the form, it just loads the default templates and throws no errors.

I also tried to just put a random string for the template path and that didn't throw any errors. Any ideas?

**Comment by hubertprein** [comment]
I'm not able to reproduce your situation. I believe there's something wrong on your end. Are you sure the template path is set correctly? If the template can't be found, it'll get the default templates instead. So you won't see an error if the path isn't correct.

**Comment by anguiac7** [comment]
Thanks for your response! So apparently it just can’t find the templates. The path works fine on my local development server and the directories are exactly the same on the staging server since I pulled it down using Git. The templates are under craft/templates/forms/amforms/field and craft/templates/forms/amforms/form and in the custom template fields I have forms/amforms/field and  forms/amforms/form.

My local dev server is a Ubuntu box whereas the staging server is a Windows server. Would that make a difference? I’ll try moving the templates just into the main craft/templates directory and see if maybe there was a problem with the path.
On January 4, 2016 at 7:26:12 AM, Hubert Prein (notifications@github.com) wrote:

I'm not able to reproduce your situation. I believe there's something wrong on your end. Are you sure the template path is set correctly? If the template can't be found, it'll get the default templates instead. So you won't see an error if the path isn't correct.

**Comment by hubertprein** [comment]
@anguiac7 After moving the templates into the main craft/templates folder, did this solve your problem?

**Comment by tcsehv** [comment]
I had the same problem when using a custom template folder (CRAFT_TEMPLATES_PATH). After moving the all templates to the default path it seemed to work.

**Comment by anguiac7** [comment]
@hubertprein yes! I'm so sorry it's taken me FOREVER to respond.
