### ISSUE TITLE
How to write a notification Template?

### ISSUE THREAD

**Issue by kaspar-allenbach** [am-impact/amforms#49]
Hi.

I have a simple form containing the standard `telephoneNumber` field.

On each send there is the message: "Craft\AmForms_FormModel doesn't have a scope telephone number"

If I add `telephoneNumber` as a mandatory field. The whole form will validate without any entries in any field. Superstrange.

I removed `telephoneNumber` altogether and now it's working fine.

**Comment by kaspar-allenbach** [comment]
Okay. I circled the problem. Its not the form. Its the notification template.

How do I have to call the fields there?
I tought of something like this:
```
{% set form = craft.amForms.getForm('contactForm') %}

Name: {{ form.name }}
Email: {{ form.emailAddress }}

-------------------------
{{ form.comment }}
-------------------------
```

But this only throws only the former error. Do you have an example of a notification template?

**Comment by hubertprein** [comment]
@kaspar-allenbach There sure is! If you check the templates folder in the plugin, take a look at: _display/templates/email.twig. This template is used by default, it not overridden from plugin / form specific settings.

**Comment by kaspar-allenbach** [comment]
Neat. Thank you.
