### ISSUE TITLE
Dynamic Subject Line

### ISSUE THREAD

**Issue by bryantAXS** [am-impact/amforms#50]
What other fields are available to dynamicaly insert into the Subject line? Are we able to use fields submitted from within the form? 

![Image](https://s3.amazonaws.com/f.cl.ly/items/151K2p2S3Z273H2e3H1z/Screen%20Shot%202016-01-21%20at%205.36.18%20PM.png?v=a106933b)

**Comment by hubertprein** [comment]
@bryantAXS Sorry for the late reply, but yes you are able to add form fields into the subject line. Make sure they are filled out though for best results :)

E.g.: {firstName} {lastName} filled out the {formName} form.
