### ISSUE TITLE
How to use the am-form field

### ISSUE THREAD

**Issue by gudehus** [am-impact/amforms#52]
I put the a form field named formular in some entries and like to show the right form in my layout.

But neither {{ entry.formular }} nor {{ craft.amForms.displayForm(entry.formular) }} is working.
What is the right syntax?

**Comment by hubertprein** [comment]
@gudehus Like this:

```
{% if entry.formulier|length %}
    {{ entry.formulier.first().displayForm() }}
{% endif %}
```

**Comment by gudehus** [comment]
That's what I needed. Thank you.
