### ISSUE TITLE
The latest version does not install

### ISSUE THREAD

**Issue by intoeetive** [am-impact/amforms#53]
I haven't been able to install latest version because of error.

Had to install first release and then update.

**Comment by hubertprein** [comment]
@intoeetive What was the error?

**Comment by intoeetive** [comment]
Sorry I did write it down, but it was related to settings expected to be array, being NULL instead

**Comment by hubertprein** [comment]
Do you happen to know from which version you tried to update?

**Comment by intoeetive** [comment]
I performed fresh install of 1.3.5 when I got the error.

I had to manually delete records in database and then install 1.0 and update it to 1.3.5 (this was successul without errors)

**Comment by hubertprein** [comment]
Can't reproduce this. If this happens again, please open a new issue :)
