### ISSUE TITLE
Display form from Form fieldtype

### ISSUE THREAD

**Issue by rickprince** [am-impact/amforms#54]
@bvangennep I'm trying to output an amform in a template that has been selected from a Form field. From the docs it says: 

    {{ craft.amForms.displayForm('formHandle') }}

My matrix fieldname is called *myFormField*: 

[![enter image description here][2]][2]

so:

    {{ craft.amForms.displayForm('{{block.myFormField}}') }}

But it doesn't look like craft is parsing *{{block.myFormField}}*:

    No form exists with the handle “{{block.myFormField}}”.

Any thoughts?

  [2]: http://i.stack.imgur.com/qTtSj.png

**Comment by hubertprein** [comment]
```
{% if block.myFormField|length %}
    {{ block.myFormField.first().displayForm() }}
{% endif %}
```

**Comment by rickprince** [comment]
Perfect! Thank you :)

**Comment by johanneslamers** [comment]
@hubertprein  Can you add this to the manual?
