### ISSUE TITLE
Placeholder on Emails Fields

### ISSUE THREAD

**Issue by kaspar-allenbach** [am-impact/amforms#56]
It would be nice if one could ad placeholder on every type of form field.

Eg. The E-Mail fieldtype dosn't seem to support placeholders.

![bildschirmfoto 2016-03-03 um 15 11 03](https://cloud.githubusercontent.com/assets/762213/13496753/4b4b19e4-e152-11e5-8918-fd95aa6360ec.png)

**Comment by PaulvanKaam** [comment]
I'm having the same problem.
For everybody who's looking for a temporary fix, you could use a little Jquery to set a placeholder:
`$('input[type="email"]').each(function( index ) {
			$(this).attr("placeholder", "E-mail");
		});`

**Comment by Wiejeben** [comment]
+1

**Comment by kaspar-allenbach** [comment]
Is it also possible to ad placeholders for numeric fields?
