### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by aelvan** [am-impact/amforms#58]
Hi, could you please add a license to the plugin? Would be good to know if you plan to keep it open, or convert it to a commercial plugin at some point.

**Comment by hubertprein** [comment]
Added in latest release.

**Comment by aelvan** [comment]
"We reserve the right, and hereby inform you, that in the future we might start charging
license fees for new versions and / or newly issued licenses for this software."

Right, that's what I wanted to know. Too bad. 👎

**Comment by hubertprein** [comment]
We're not sure what the future holds, so we would like to keep our options open.
