### ISSUE TITLE
Form not submitting as expected

### ISSUE THREAD

**Issue by aev-hatlehols** [am-impact/amforms#59]
When submitting a form using amforms it sometimes reloads with the parameter ?submitted=0 instead of ?submitted=myform

This results in a not submitted form, and it can be difficult for users to understand if the form was submitted or not.

**Comment by hubertprein** [comment]
When that happens, it has been marked as **spam**. The plugin will notice when a submission has been send in to fast, is a duplicate, honeypot has been entered, etc.. Upon submission, it will still redirect you and tells that is has been "successful" to fool spammers, but really it didn't succeed.

In your case, it feels like the user has submitted the form, twice. It probably succeeded the first attempt, but also recognises the second submission, which results in the URL **?submitted=0**
