### ISSUE TITLE
Name field name

### ISSUE THREAD

**Issue by chadcrowell** [am-impact/amforms#60]
I tried to change the label for the Name field to Your Name and it wouldn't save, because "name" is a reserved word in Craft. You may want to change that default field name so the other aspects of that field can be changed.

**Comment by hubertprein** [comment]
Ahh right. We never have this issue, because when you install the plugin, the fields are translated to you primary locale. In our case **NL**, which means we don't use **name** as a field handle.

Guess I'm going to have to call it something like: fullName :)

It's on the todo list!

**Comment by hubertprein** [comment]
Fixed in latest release.
