### ISSUE TITLE
Feature request: add support for categories field

### ISSUE THREAD

**Issue by oadslug** [am-impact/amforms#62]
I see that there is an advanced 'entries' field. It would be great if there was also an advanced 'categories' field.

In the meantime, I am trying to set up a dynamic drop-down list based on category titles/slugs — what is the best way to accomplish this? Perhaps create a dummy drop down field (with no options defined), and then build my own options list on the front-end using craft data? I'll try that, but if anyone has a better solution please let me know. Thanks. 

[Update: the dummy dropdown solution above doesn't work. Although it submits the data correctly it does not show up in the CMS when reviewing the submitted form data, because the list is obviously empty. Using a dummy text field seems to work however.]

Btw... the am-forms plugin is great. Huge thank you!

**Comment by hubertprein** [comment]
You can now add a categories field in the latest release.
