### ISSUE TITLE
Depreciation Errors with Craft 2.6.2779

### ISSUE THREAD

**Issue by bgarrant** [am-impact/amforms#63]
I am getting a ton of these when using A&M Forms now with Craft 2.6.2779.  Looks like a change in Craft was made and the Forms plugin needs to be updated.

PathService::setTemplatesPath() has been deprecated. Use TemplatesService::setTemplatesPath() or TemplatesService::setTemplateMode() instead.

**Comment by lindseydiloreto** [comment]
@bgarrant: Glad you reported this! Those errors are a nuisance.

@amimpact: Take a look at [this SE thread...](http://craftcms.stackexchange.com/a/14380/45) @khalwat came up with a great solution which fixes the error message, while allowing backwards-compatibility for folks running earlier versions of Craft.

**Comment by hubertprein** [comment]
@bgarrant Thanks for reporting this! Will release a fix.

**Comment by bgarrant** [comment]
@khalwat is always coming up with good ideas.  Thx Hubert.

**Comment by hubertprein** [comment]
@bgarrant @lindseydiloreto Fixed in the latest release.

**Comment by bgarrant** [comment]
Thx so much Hubert

**Comment by lindseydiloreto** [comment]
Great, thanks @hubertprein!
