### ISSUE TITLE
Including an asset file causes submission to break.

### ISSUE THREAD

**Issue by onebrightlight** [am-impact/amforms#64]
When I try to submit a form with an asset field attached to it, I get the following error:

`array_merge(): Argument #1 is not an array`

The field is limited to a single asset upload, and is a required field, though I have noted that it has a separate issue if I make it not required:

```CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`bluechiptek`.`craft_relations`, CONSTRAINT `craft_relations_targetId_fk` FOREIGN KEY (`targetId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `craft_relations` (`fieldId`, `sourceId`, `sourceLocale`, `targetId`, `sortOrder`, `dateCreated`, `dateUpdated`, `uid`) VALUES (:row0_col0, :row0_col1, NULL, :row0_col3, :row0_col4, :row0_col5, :row0_col6, :row0_col7). Bound with :row0_col0='197', :row0_col1='1031', :row0_col3='Web Architecture - 11 March 2015 - BlueChipTek.pdf', :row0_col4=1, :row0_col5='2016-04-01 18:47:48', :row0_col6='2016-04-01 18:47:48', :row0_col7='d6576550-7caa-48e6-a13a-12c1f2a94acc'```

If I set the field to not be required and just ignore that field, the form submits as expected.

**Comment by hubertprein** [comment]
Which version are you running? I can't seem to reproduce this running the latest version.

As long as your file upload field looks (something) like below, it should work fine.

```
<input type="file" id="fields-file" name="fields[file][]">
```

**Comment by onebrightlight** [comment]
I'm running on Craft 2.6.2779 and a&m Forms 1.3.5 on PHP 5.4.4.2

**Comment by onebrightlight** [comment]
For reference, here’s the entire code for the form:

```
{% macro errorList(errors) %}
    {% if errors %}
        <ul class="errors">
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}

{% from _self import errorList %}

{% set form = craft.amForms.getForm('careerApplicationForm') %}

<form method="post" class="careerApplication" action="" accept-charset="UTF-8">
    {{ getCsrfInput() }}

    <input type="hidden" name="action" value="amForms/submissions/saveSubmission">

    <input type="hidden" name="handle" value="{{ form.handle }}">
    <input type="hidden" name="fields[positionAppliedFor]" value="{{ entry.title }}">

    {{ craft.amForms.displayAntispam() }}

    {{ craft.amForms.displayRecaptcha() }}

    <h3>Apply for Position: {{ entry.title }}</h3>
    <div class="fieldRow">
        <div class="field">
            {{ form.displayField('firstName') }}
        </div>
        <div class="field">
            {{ form.displayField('lastName') }}
        </div>
        <div class="field">
            {{ form.displayField('emailAddress') }}
        </div>
        <div class="field">
            <label for="coverLetterAndOrResume">Cover Letter with Resume<sup>*</sup></label>
			<input type="file" id="coverLetterAndOrResume" name="fields[coverLetterAndOrResume][]">
            {% if careerApplicationForm is defined %}
				{{ errorList(careerApplicationForm.getErrors('coverLetterAndOrResume')) }}
			{% endif %}
        </div>
        <div class="field">
            <input type="submit" value="Submit">
        </div>
</form>
```

**Comment by onebrightlight** [comment]
I can confirm that I'm getting the same issues on a staging server running PHP 5.4.45

**Comment by onebrightlight** [comment]
It also looks like I’m not the only person with this issue: https://github.com/am-impact/amforms/issues/29#issuecomment-199056511

**Comment by hubertprein** [comment]
@onebrightlight I've been testing the shit out of the plugin and honestly, could not reproduce it. Then I took a close look again at your manually created form, and eventually noticed you're forgetting something that's easily forgot.. The enctype attribute! :)

Place this in your form tag, and you're set to go: `enctype="multipart/form-data"`

**Comment by onebrightlight** [comment]
That was it! Thank you very much. I didn't realize this was needed until just now!
