### ISSUE TITLE
Custom Submission Title Format

### ISSUE THREAD

**Issue by tyler-deboer** [am-impact/amforms#67]
I have a feedback form that I'm embedding on every page inside of a structure (it's a Support-style section, so I'm using the form to gather feedback for each article). Is there a way to change the submission Title Format to display the title of the entry the form is embedded on instead of the default `{dateCreated|date('D, d M Y H:i:s')}`? I've tried using `{entry.title}` but it gives me an error saying the variable `entry` doesn't exist. I feel like maybe I'm missing something obvious with this?

Great plugin btw!

**Comment by hubertprein** [comment]
Create an Entry field in amforms, and add that to your feedback form. In the Title Format, enter the following: ```{yourCreatedEntryFieldHadle.first().title}```

**Comment by tyler-deboer** [comment]
That doesn't seem to be doing the trick. I don't think I explained my problem very well, that's my mistake! 

I'm using the same form throughout every page. When you view the form submissions you just get titles like this `Mon, 02 May 2016 15:38:28` that you end up having to click into to view the exact page the submission came from (on the **Submitted from** section in the sidebar).  

It's not a huge deal, but it would be nice if there would be a way to see the "Submitted From" section at a glance, or set up the submission title field to display the "Submitted From" page title instead of the default `Mon, 02 May 2016 15:38:28` format.

**Comment by hubertprein** [comment]
There's no easy / fast way to see which submissions came from a specific entry at a glance, but with the suggestion I gave before, you can at least see on which entry it was submitted. You can then see this when viewing a submission in the CP, or adjust the notification template slightly, so it'll display titles of relations rather than IDs.
