### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by aaronsransom** [am-impact/amforms#68]
Hey-

Trying to get your plugin to install but Craft isn't recognizing that a plugin is even available to install from settings. I've uploaded the master file to plugins. I haven't an issue installing the Craft Contact Form or others, just this one.

Am I supposed to be stripping files from amforms-master before uploading?

**Comment by hubertprein** [comment]
Create a folder in the plugins directory, and name that **amforms**. Put the contents of the downloaded zip file, in that created folder.

**Comment by aaronsransom** [comment]
Awesome! Worked perfectly and thank you for the immediate response!
