### ISSUE TITLE
Custom Notifications

### ISSUE THREAD

**Issue by theswebsite** [am-impact/amforms#69]
Hi,

Is there any documentation on how to produce a custom notification containing data from the posted form?

Thanks

**Comment by hubertprein** [comment]
There is no documentation for that at the moment.

However, if you take a look at the following template: `amforms/templates/_display/templates/email.twig`. That template is the default that's being used when sending a notification. If you copy the contents of it and create your own folder/template in the Craft site template's folder (E.g.: `craft/templates/_amforms/email.twig`) you can do your own thing with the possible variables given from the default template.
