### ISSUE TITLE
Dynamic Form Recipients

### ISSUE THREAD

**Issue by ryan4303** [am-impact/amforms#70]
Is there a way to have a select field in a form that depending on which option is selected changes the 
email that receives the email notification?

Thanks.

**Comment by hubertprein** [comment]
Sure. Not the most fancy way, but you could create a dropdown field with the email addresses as values. In your notification receiver field, put in the handle of the field. `{fieldHandleHere}`

E.g.: http://cl.ly/1o1946253V06

**Comment by ryan4303** [comment]
This worked, thank you.
