### ISSUE TITLE
Custom template for input fields

### ISSUE THREAD

**Issue by luke-nehemedia** [am-impact/amforms#75]
Hello

I figured out how to overwrite the form/field/email/tab-templates and this just went fine. However, I am not able to modify e.g. the class of an input-field. Is this possible?

I copied the whole _display/templates/ folder to my templates folder, however, a change I make in _components/fieldtypes/PlainText/input.twig will not be recognized. 

Is it possible to change this or do I have to overwrite the plugins own template?

**Comment by hubertprein** [comment]
@luke-nehemedia You're right. For now, the plugin doesn't support to overwrite the actual field. Just the container around it.

**Comment by jsunsawyer** [comment]
@hubertprein Do you know of a way we could create custom templates in the meantime? I'd prefer to not edit any plugin files if I can help it.

I'm trying to duplicate the whole display templates folder in my templates folder and overwrite the fields template to pull in custom input field templates when needed.

```
{% if type in ["test","something","dropdown"] %}
  {% switch type %}
    {% case "dropdown" %}
      {% include "_includes/forms/select" with config only %}
  {% endswitch %}
{% else %}
  {{ input|raw }}
{% endif %}
```
I'm just not sure how to set config to return real content.
