### ISSUE TITLE
Cant view files uploaded. I get an asset view of the file

### ISSUE THREAD

**Issue by bumstyla** [am-impact/amforms#80]
Thanks for the great work. When i see the file in the submissions i see the File field. but i cant download the file itself.

**Comment by rswhite7** [comment]
Have you checked the Assets group you assigned the assets field to?  If you go to Assets > Name_of_assets_group and click on the uploaded image, you can then click the gear for a download of options.  There you can choose to download the image.

<img width="839" alt="screen shot 2016-08-04 at 5 22 10 pm" src="https://cloud.githubusercontent.com/assets/13842870/17407574/10f6f3fa-5a68-11e6-910b-406f4ae06000.png">

**Comment by hubertprein** [comment]
@bumstyla Exactly what @rswhite7 said. You can download files from the assets overview. You can't download them from an asset field itself.

**Comment by Gnative** [comment]
Maybe create a duplicate of the asset field with an additional button for downloading to attached file to use in the form view. Or, search a for assets fields and add a section for files to download. If i can find some spare time soon i'll have a look.
