### ISSUE TITLE
Possible feature: Allow admins to embed a particular form from a form fieldtype

### ISSUE THREAD

**Issue by andregoldstein** [am-impact/amforms#84]
Hi there,

I'm just wondering if this would be possible somehow in the future if a user can make their own form and we can allow a "form" fieldtype on a particular entry type. They could then select from one of their forms and we could handle the code to embed on that page?

Failing that is there any possible workaround for us to achieve something similar manually?

Thanks!

**Comment by hubertprein** [comment]
Not a 100% sure I understand what you require. If you want to be able to choose a form on an Entry for example, that is already possible. Simply add a new Craft field and choose for the "Form" option. That'll let you choose a form.

In Twig:
```
{% if entry.createdFormHandleHere|length %}
    {{ entry.createdFormHandleHere.first().displayForm() }}
{% endif %}
```

Is that what you were looking for?

**Comment by andregoldstein** [comment]
Extremely belated thanks for this Hubert. Didn't realise a form field came with the plugin
