### ISSUE TITLE
Field template example?

### ISSUE THREAD

**Issue by migswd** [am-impact/amforms#87]
I do not see how to use the field template.
Could you provide an example please?

![screen shot 2016-08-17 at 16 10 48](https://cloud.githubusercontent.com/assets/3531623/17739382/34f0eca2-6495-11e6-9fa8-1888a117c406.jpg)

**Comment by hubertprein** [comment]
Please take a look at `amforms/templates/_display/templates/field.twig` that's the template you can overwrite.
