### ISSUE TITLE
Checkbox always on Yes

### ISSUE THREAD

**Issue by kaspar-allenbach** [am-impact/amforms#88]
I have a checkbox field:

![bildschirmfoto 2016-08-22 um 15 06 44](https://cloud.githubusercontent.com/assets/762213/17855653/175abda6-687a-11e6-86d5-83457555555d.png)

I add the field like this:

`{{ form.displayField('newsletter') }}`

This always results in "Yes" even if the checkbox isn't checked. Is this a bug, or is the configuration wrong?

**Comment by hubertprein** [comment]
Your default value is "Yes" (see your checked box on the right) so yeah, that's the desired result then. I'd make a light switch for this though, and simply use your own HTML to create the checkbox on the front-end.
