### ISSUE TITLE
Setting Dynamic Email Recipients

### ISSUE THREAD

**Issue by oadslug** [am-impact/amforms#99]
If you have a moment, I could use your help. I'm trying to define dynamic email recipients based on form checkbox selections, by setting a hidden field called 'notificationRecipients' via javascript. I am currently following the general instructions provided here: [https://github.com/am-impact/amforms/issues/86] and [https://github.com/am-impact/amforms/issues/72].

This is the current setup:
- defined a custom form field (text field) with the handle 'notificationRecipients'.
- added the field to my form template:

```
<input type="hidden" name="fields[notificationRecipients]" value="">
```

- 'notificationRecipients' value is being set as a comma separated list via javascript based on checkbox selections made by the user (confirmed working).
- in the form settings, I set the "Email Recipients" field to:

```
default-address@domain.com,{notificationRecipients}
```

- I have also tried adding the 'notificationRecipients' field to the form field layout (which made no difference).

It is sending to the hard coded`default@company.com` email address. But as far as I can tell it is not sending to any of the dynamic recipients defined in the `notificationRecipients` field.

Any ideas? What am I missing?

I need to also add — awesome plugin. Thank you so much for making this (and all your plugins) available and for all your work! Very much appreciated.

— Douglas

**Comment by hubertprein** [comment]
@oadslug Thanks for the compliment!

Sorry, didn't have the time to react earlier, but has this issue been resolved? What you must do, is to make sure that the **notificationRecipients** is added to the field layout. Without that, it's not working at all.

You should be able to see what data is available in **notificationRecipients** when you submit the form, since it's saved in the submission. Perhaps a bug in the JS even?

**Comment by oadslug** [comment]
No bug in the JS. There may have been a problem sending to multiple addresses? — I don't know. Regardless, I upgraded to the latest version and it seems to work now. Thanks again. Very much appreciated!
